### PR TITLE
Sam cli entry point

### PR DESCRIPTION
**Pull request by samphillips1879**
# Description
This establishes the entry point to the Bangazon CLI.
# Related Ticket(s)
List related ticket(s) that apply to the work done in this pull request
#1, #3 
## Testing

[ ] There are new unit tests in this PR, and I verify that there is full coverage of all new code.
[x] I certify that all existing tests pass

## Documentation

[x] There is new documentation in this pull request that must be reviewed..

## Deploy Notes

```sh
git pull --prune
git checkout <feature_branch>
```

## Steps to Test
Outline the steps to test the code in this pull request.

1. From the root of the project, run ```python main.py```

### CODE REVIEW

**Comment by juliakimchung** [comment]
👍 looks good!

**Review by danirenae — APPROVED** [review]
pulled down and tested! Works fine! 👍

**Review by danirenae — APPROVED** [review]
works! 👍

**Comment by pinkston4** [comment]
👍

**Pull request merged**
