### PR TITLE
Da cli refactor

### LINKED ISSUE #19: Create UI/CLI for Active Customer
## Expected Behavior
Here the user will be able to interface with the active customer prompts on the command line. The command line prompts view will look like the following:

```
Which customer will be active?
1. John Q. Public
2. Svetlana Z. Herevazena
>
```

## Actual Behavior
The user will interface with the active customer prompts by choosing a customer as active from the list.

## Module Suspected / Relevant Files 
- There should be a module that interacts with the main CLI and the customer module

## Related Issues 
Issue #1 and #3

### PR DESCRIPTION
**Pull request by danirenae**
# Description
Refactored the payment CLI so that the customer ID is attached to the payment. If the customer has not yet chosen an active customer then they are prompted to do so before they can add payment type.

# Related Ticket(s)
This is related to ticket number #1 
Fixed #19 

## Testing
[x] There are no new tests in this PR
[ ] There are new unit tests in this PR, and I verify that there is full coverage of all new code.
[ ] I certify that all existing tests pass

## Documentation
[x] There is no new documentation
[ ] There is new documentation in this pull request that must be reviewed..

## Deploy Notes

```sh
git fetch --all
git checkout da-cli
```

## Steps to Test
Test as follows:
Go into the main file bangazon-cli and run:
```
python main.py
```

### CODE REVIEW

**Comment by samphillips1879** [comment]
Reconfigure database path using configuration.py file

**Comment by samphillips1879** [comment]
Looks great! 👍 tests pass on my machine, and I'm able to save new payments to the database 💯

**Comment by pinkston4** [comment]
💯

**Comment by juliakimchung** [comment]
👍 Yay! We can save new payments! Great Job!

**Pull request merged**
